services:
  subscription-page:
    image: ${DOCKERHUB_USERNAME:-frvrsd}/subscription-page:latest
    container_name: subscription-page
    hostname: subscription-page
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '127.0.0.1:3010:3010'
    networks:
      - remnawave-network

networks:
  remnawave-network:
    driver: bridge
    external: true
